'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Lander.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderCrash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderCrash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderCrashGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderCrashGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderHalfThrusting0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderHalfThrusting0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderHalfThrusting0Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderHalfThrusting0Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderHalfThrusting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderHalfThrusting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderHalfThrusting1Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderHalfThrusting1Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderHalfThrusting2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderHalfThrusting2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderHalfThrusting2Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderHalfThrusting2Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderHalfThrusting3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderHalfThrusting3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderHalfThrusting3Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderHalfThrusting3Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderHalfThrusting4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderHalfThrusting4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderHalfThrusting4Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderHalfThrusting4Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderIdleUpright___Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderIdleUpright___Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderIdleUpright___White() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderIdleUpright___White", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderNormal0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderNormal0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderNormal0Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderNormal0Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderNormal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderNormal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderNormal1Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderNormal1Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderNormal2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderNormal2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderNormal2Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderNormal2Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderNormal3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderNormal3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderNormal3Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderNormal3Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderNormal4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderNormal4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderNormal4Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderNormal4Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderThrusting0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderThrusting0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderThrusting0Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderThrusting0Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderThrusting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderThrusting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderThrusting1Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderThrusting1Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderThrusting2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderThrusting2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderThrusting2Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderThrusting2Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderThrusting3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderThrusting3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderThrusting3Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderThrusting3Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderThrusting4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderThrusting4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LanderThrusting4Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LanderThrusting4Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MoonMachine__Version_2_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MoonMachine__Version_2_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MoonMachine__Version_2_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MoonMachine__Version_2_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MoonMachine__Version_2_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MoonMachine__Version_2_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MoonMachine__Version_2_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MoonMachine__Version_2_3", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
